# -*- coding: utf-8 -*-
"""Hdd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H932387RsNyU6vAAmoa8Ky4W5lqli59A

HEART DISEASE DETECTION using MACHINE LEARNING
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

df=pd.read_csv('/heart_disease_data.csv')

df.head()

df.tail()

df.shape

df.info()

df.describe()

df['target'].value_counts()

"""0 = Healthy ;
1 = Unhealthy **bold text**
"""

x =df.drop(columns='target',axis=1)
x

y = df['target']
y

"""Splitting dataset into Train & Test"""

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,stratify=y,random_state=23)

print(x_train.shape,x_test.shape)

"""Model Training"""

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(x_train,y_train)

y_pred = model.predict(x_test)

accuracy_score(y_pred,y_test)

print("The Accuraccy score is ",accuracy_score)

"""Building a Predictive System"""

input_data = (62,0,0,140,268,0,0,160,0,3.6,0,0,2)

arr = np.array(input_data)

print(arr)

prediction = model.predict(arr.reshape(1,-1))

print(prediction)

if prediction == 0:
  print("The person is Healthy")
else:
  print("The person is Unhealthy")